### ISSUE TITLE
Process.GetProcessByName() Inject Error

### ISSUE THREAD

**Issue by Shitric** [Reloaded-Project/Reloaded.Injector#1]
`Process[] p = Process.GetProcessesByName("notepad");
 Injector injector = new Injector(p);`

Process does not accept a process of type [].

**Comment by Sewer56** [comment]
Accepting an array of processes as an argument wouldn't make logical sense, unless you would want to operate over all instances at the same time.

For the purpose of this library, writing a class which performs all operations on a set rather than individual item would probably be unnecessary rarely used boilerplate code making the library size larger.

Anyway, consider using a for/foreach loop to just make an `Injector` for every instance.

Alternatively you can do it with a LINQ one liner:
```csharp
Injector[] injectors = Process.GetProcessesByName("notepad").Select(x => new Injector(x)).ToArray();
```
